using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.VFX;

public class UnitSpawnAnimationController
{
    private SkinnedMeshRenderer[] renderers;
    public void SpawnUnit(GameObject unit, bool isPlayerOwned, float spawnDuration, bool disableComponent)
    {
        GameObject unitRootGameObject = unit.transform.root.gameObject;
        VisualEffect effect = unitRootGameObject.GetComponentInChildren<VisualEffect>();
        //GameObject meshRendererOwner = null;
        if (effect != null)
        {
            //MeshFilter meshFilter = unit.transform.root.GetComponentInChildren<MeshFilter>(true);
            Mesh unitMesh = CombineSkinnedMeshToMesh(unitRootGameObject);
            //meshRendererOwner = meshFilter.gameObject;

            effect.SetFloat("LifeTimeInput", spawnDuration);
            effect.SetMesh("MeshToCreate", unitMesh);
        }
        else
        {
            Debug.LogError($"{unit.name} is missing VisualEffect component!");
        }
        if (disableComponent)
        {
            UnitMonoMule.Instance.StartCoroutine(PlayVFXWithDisable(effect, unit, spawnDuration));
        }
        else
        {
            effect.enabled = true;
        }
    }
    private IEnumerator PlayVFXWithDisable(VisualEffect effect, GameObject gameObject, float duration)
    {
        effect.enabled = true;
        if (renderers == null || renderers.Length <= 0)
        {
            Debug.LogError("No SkinnedMesh Found!");
            UnitMonoMule.Instance.StopCoroutine("PlayVFXWithDisable");
        }
        foreach (SkinnedMeshRenderer renderer in renderers)
        {
            renderer.gameObject.SetActive(false);
        }
        yield return new WaitForSeconds(duration);
        effect.enabled = false;
        foreach (SkinnedMeshRenderer renderer in renderers)
        {
            renderer.gameObject.SetActive(true);
        }
    }

    // Mostly generated by CHATGPT: https://chatgpt.com/s/t_68bbae53535081918bb6a83f68eb4e09
    // With followup: https://chatgpt.com/s/t_68bc8b0ea2a08191ad733f7b459fa4df
    // with baking transform fix: https://chatgpt.com/s/t_68bc9fb1bd3881919e5f9102591c4b9c
    private Mesh CombineSkinnedMeshToMesh(GameObject gameObject)
    {
        renderers = gameObject.GetComponentsInChildren<SkinnedMeshRenderer>(true);
        List<CombineInstance> combines = new();
        foreach (SkinnedMeshRenderer skinnedMesh in renderers)
        {
            Mesh baked = new();
            skinnedMesh.BakeMesh(baked, true);

            CombineInstance combineInstance = new();
            combineInstance.mesh = baked;
            // Keeps the baked mesh aligned with the gameobject.
            combineInstance.transform = gameObject.transform.worldToLocalMatrix * skinnedMesh.transform.localToWorldMatrix;
            combines.Add(combineInstance);
        }

        Mesh finalMesh = new();
        finalMesh.name = "Combined Mesh";
        finalMesh.CombineMeshes(combines.ToArray(), true, true);

        finalMesh.RecalculateNormals();
        finalMesh.RecalculateBounds();

        //MeshRenderer meshRenderer = gameObject.transform.root.GetComponentInChildren<MeshRenderer>(true);
        //MeshFilter meshFilter = gameObject.transform.root.GetComponentInChildren<MeshFilter>(true);
        //meshFilter.sharedMesh = finalMesh;
        //meshRenderer.sharedMaterial = renderers[0].sharedMaterial;

        return finalMesh;
    }
}
